CREATE TABLE clients (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, phone VARCHAR(50), email VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE travel_requests (id INT AUTO_INCREMENT PRIMARY KEY, client_id INT NOT NULL, destination VARCHAR(255) NOT NULL, budget DECIMAL(12,2), status VARCHAR(50) DEFAULT 'new', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE tours (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, country VARCHAR(255), price DECIMAL(12,2), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE communications (id INT AUTO_INCREMENT PRIMARY KEY, client_id INT NOT NULL, channel VARCHAR(50), message TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
